use_frameworks!

platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'OldDemoViewModel_Example' do
  
  target 'OldDemoViewModel_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
